--------------------------------------------------------
--  ������ ������ - ȭ����-9��-03-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CART_HISTORY
--------------------------------------------------------

  CREATE TABLE "MAINPROJECT"."CART_HISTORY" 
   (	"CART_HISTORY_ID" NUMBER, 
	"USER_ID" NUMBER, 
	"PRODUCT_ID" NUMBER, 
	"ACTION" VARCHAR2(10 BYTE), 
	"ACTION_DATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CATEGORIES
--------------------------------------------------------

  CREATE TABLE "MAINPROJECT"."CATEGORIES" 
   (	"CATEGORY_ID" NUMBER, 
	"CATEGORY_NAME" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ORDERS
--------------------------------------------------------

  CREATE TABLE "MAINPROJECT"."ORDERS" 
   (	"ORDER_ID" NUMBER, 
	"USER_ID" NUMBER, 
	"ORDER_DATE" DATE DEFAULT SYSDATE, 
	"TOTAL_AMOUNT" NUMBER, 
	"CITY" VARCHAR2(100 BYTE), 
	"STREET_ADDRESS" VARCHAR2(255 BYTE), 
	"DETAILS" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ORDER_ITEMS
--------------------------------------------------------

  CREATE TABLE "MAINPROJECT"."ORDER_ITEMS" 
   (	"ORDER_ITEM_ID" NUMBER, 
	"ORDER_ID" NUMBER, 
	"PRODUCT_ID" NUMBER, 
	"QUANTITY" NUMBER DEFAULT 1, 
	"PRICE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRODUCTS
--------------------------------------------------------

  CREATE TABLE "MAINPROJECT"."PRODUCTS" 
   (	"PRODUCT_ID" NUMBER, 
	"PRODUCT_NAME" VARCHAR2(255 BYTE), 
	"CATEGORY_ID" NUMBER, 
	"PRICE" NUMBER, 
	"STOCK_QUANTITY" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRODUCT_DESCRIPTIONS
--------------------------------------------------------

  CREATE TABLE "MAINPROJECT"."PRODUCT_DESCRIPTIONS" 
   (	"DESCRIPTION_ID" NUMBER, 
	"PRODUCT_ID" NUMBER, 
	"LANGUAGE" VARCHAR2(10 BYTE), 
	"DESCRIPTION" VARCHAR2(2000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "MAINPROJECT"."USERS" 
   (	"USER_ID" NUMBER, 
	"USERNAME" VARCHAR2(100 BYTE), 
	"EMAIL" VARCHAR2(255 BYTE), 
	"PASSWORD" VARCHAR2(255 BYTE), 
	"PHONE_NUMBER" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USER_VIEWS
--------------------------------------------------------

  CREATE TABLE "MAINPROJECT"."USER_VIEWS" 
   (	"VIEW_ID" NUMBER, 
	"USER_ID" NUMBER, 
	"PRODUCT_ID" NUMBER, 
	"VIEWED_AT" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into MAINPROJECT.CART_HISTORY
SET DEFINE OFF;
REM INSERTING into MAINPROJECT.CATEGORIES
SET DEFINE OFF;
REM INSERTING into MAINPROJECT.ORDERS
SET DEFINE OFF;
REM INSERTING into MAINPROJECT.ORDER_ITEMS
SET DEFINE OFF;
REM INSERTING into MAINPROJECT.PRODUCTS
SET DEFINE OFF;
REM INSERTING into MAINPROJECT.PRODUCT_DESCRIPTIONS
SET DEFINE OFF;
REM INSERTING into MAINPROJECT.USERS
SET DEFINE OFF;
REM INSERTING into MAINPROJECT.USER_VIEWS
SET DEFINE OFF;
--------------------------------------------------------
--  Constraints for Table ORDER_ITEMS
--------------------------------------------------------

  ALTER TABLE "MAINPROJECT"."ORDER_ITEMS" ADD PRIMARY KEY ("ORDER_ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MAINPROJECT"."ORDER_ITEMS" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "MAINPROJECT"."ORDER_ITEMS" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
  ALTER TABLE "MAINPROJECT"."ORDER_ITEMS" MODIFY ("ORDER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "MAINPROJECT"."USERS" ADD UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MAINPROJECT"."USERS" ADD PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MAINPROJECT"."USERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "MAINPROJECT"."USERS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "MAINPROJECT"."USERS" MODIFY ("USERNAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CART_HISTORY
--------------------------------------------------------

  ALTER TABLE "MAINPROJECT"."CART_HISTORY" ADD PRIMARY KEY ("CART_HISTORY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MAINPROJECT"."CART_HISTORY" ADD CHECK (ACTION IN ('ADD', 'REMOVE')) ENABLE;
  ALTER TABLE "MAINPROJECT"."CART_HISTORY" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
  ALTER TABLE "MAINPROJECT"."CART_HISTORY" MODIFY ("USER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ORDERS
--------------------------------------------------------

  ALTER TABLE "MAINPROJECT"."ORDERS" ADD PRIMARY KEY ("ORDER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MAINPROJECT"."ORDERS" MODIFY ("TOTAL_AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "MAINPROJECT"."ORDERS" MODIFY ("USER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUCTS
--------------------------------------------------------

  ALTER TABLE "MAINPROJECT"."PRODUCTS" ADD PRIMARY KEY ("PRODUCT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MAINPROJECT"."PRODUCTS" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "MAINPROJECT"."PRODUCTS" MODIFY ("PRODUCT_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUCT_DESCRIPTIONS
--------------------------------------------------------

  ALTER TABLE "MAINPROJECT"."PRODUCT_DESCRIPTIONS" ADD PRIMARY KEY ("DESCRIPTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MAINPROJECT"."PRODUCT_DESCRIPTIONS" MODIFY ("LANGUAGE" NOT NULL ENABLE);
  ALTER TABLE "MAINPROJECT"."PRODUCT_DESCRIPTIONS" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USER_VIEWS
--------------------------------------------------------

  ALTER TABLE "MAINPROJECT"."USER_VIEWS" ADD PRIMARY KEY ("VIEW_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MAINPROJECT"."USER_VIEWS" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
  ALTER TABLE "MAINPROJECT"."USER_VIEWS" MODIFY ("USER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CATEGORIES
--------------------------------------------------------

  ALTER TABLE "MAINPROJECT"."CATEGORIES" ADD PRIMARY KEY ("CATEGORY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MAINPROJECT"."CATEGORIES" MODIFY ("CATEGORY_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CART_HISTORY
--------------------------------------------------------

  ALTER TABLE "MAINPROJECT"."CART_HISTORY" ADD FOREIGN KEY ("USER_ID")
	  REFERENCES "MAINPROJECT"."USERS" ("USER_ID") ENABLE;
  ALTER TABLE "MAINPROJECT"."CART_HISTORY" ADD FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "MAINPROJECT"."PRODUCTS" ("PRODUCT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORDERS
--------------------------------------------------------

  ALTER TABLE "MAINPROJECT"."ORDERS" ADD FOREIGN KEY ("USER_ID")
	  REFERENCES "MAINPROJECT"."USERS" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORDER_ITEMS
--------------------------------------------------------

  ALTER TABLE "MAINPROJECT"."ORDER_ITEMS" ADD FOREIGN KEY ("ORDER_ID")
	  REFERENCES "MAINPROJECT"."ORDERS" ("ORDER_ID") ENABLE;
  ALTER TABLE "MAINPROJECT"."ORDER_ITEMS" ADD FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "MAINPROJECT"."PRODUCTS" ("PRODUCT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUCTS
--------------------------------------------------------

  ALTER TABLE "MAINPROJECT"."PRODUCTS" ADD FOREIGN KEY ("CATEGORY_ID")
	  REFERENCES "MAINPROJECT"."CATEGORIES" ("CATEGORY_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUCT_DESCRIPTIONS
--------------------------------------------------------

  ALTER TABLE "MAINPROJECT"."PRODUCT_DESCRIPTIONS" ADD FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "MAINPROJECT"."PRODUCTS" ("PRODUCT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USER_VIEWS
--------------------------------------------------------

  ALTER TABLE "MAINPROJECT"."USER_VIEWS" ADD FOREIGN KEY ("USER_ID")
	  REFERENCES "MAINPROJECT"."USERS" ("USER_ID") ENABLE;
  ALTER TABLE "MAINPROJECT"."USER_VIEWS" ADD FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "MAINPROJECT"."PRODUCTS" ("PRODUCT_ID") ENABLE;


CREATE SEQUENCE user_id_seq
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE TABLE cart_items (
    user_id NUMBER,                      -- 사용자 ID (외래키)
    product_id NUMBER,                   -- 제품 ID (외래키)
    quantity NUMBER DEFAULT 1,           -- 제품 수량
    price NUMBER,                        -- 제품 가격 (복사된 가격)
    PRIMARY KEY (user_id, product_id),   -- 복합 기본키
    CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT fk_product_id FOREIGN KEY (product_id) REFERENCES products (product_id)
);

